### PR TITLE
Make use of translated definition error messages 

### PR DESCRIPTION
**Pull request by Goltergaul**
this will improve the error message quality

### CODE REVIEW

**Comment by Goltergaul** [comment]
@andreaseger can i remove the support for ruby 2.4 and 2.5? both are EOL, would add 2.6,2.7

**Comment by Goltergaul** [comment]
@andreaseger the builds fail with `/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/octokit-4.22.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/runtastic/request_handler/pulls/51: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)` any idea?

**Comment by andreaseger** [comment]
not quickly and I'd need to dig into what exactly is going on, but you can probably just remove `danger` from the ci pipeline ( removing https://github.com/runtastic/request_handler/blob/master/.circleci/config.yml#L22 )

**Comment by andreaseger** [comment]
> @andreaseger can i remove the support for ruby 2.4 and 2.5? both are EOL, would add 2.6,2.7

sure

**Comment by Goltergaul** [comment]
Ready for final review now

**Review by ThomasKoppensteiner — APPROVED** [review]

**Review by andreaseger — APPROVED** [review]

**Pull request merged**
